version: '3.7'

services:
  swarm:
    image: mithrand0/reactive-drop-linux-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - "port=27050"
      - "maxplayers=4"
      - "rd_hostname=Reactive Drop Linux server"
      - "rd_rcon_password=swarmtest"
      - "wine_fastsync=1"
    networks:
      - network
    ports:
      - "27050:27050 /tcp"
      - "27050:27050 /udp"
    volumes:
      - "/dev/winesync:/dev/winesync"
      - "reactivedrop:/usr/lib/games/reactivedrop"

volumes:
  reactivedrop:

networks:
  network:
