
name: CI-stable

on:
  push:
    branches: [master]
  repository_dispatch:
    types: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # github registry
      - name: ghcr.io login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: ghcr.io build & push
        id: github_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      # docker hub
      - name: docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker hub build & push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ github.repository }}:latest