
name: CI-testing

on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [testbuild]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build & Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:testing
      - name: Deploy
        uses: indiesdev/curl@v1
        with:
          url: ${{ secrets.DEPLOY_HOST }}/ghcr.io/${{ github.repository }}:testing
          basic-auth: ${{ secrets.DEPLOY_AUTH }}
          timeout: 20000
